// Create web server
// 1. npm install express --save
// 2. npm install body-parser --save
// 3. npm install cookie-parser --save
// 4. npm install express-session --save
// 5. npm install express-handlebars --save
// 6. npm install multer --save
// 7. npm install nodemailer --save
// 8. npm install mysql --save
// 9. npm install mysql --save
// 10. npm install connect-mysql --save
// 11. npm install passport --save
// 12. npm install passport-local --save
// 13. npm install passport-facebook --save
// 14. npm install passport-twitter --save
// 15. npm install passport-google-oauth --save
// 16. npm install passport-http-bearer --save
// 17. npm install passport-jwt --save
// 18. npm install bcrypt-nodejs --save
// 19. npm install connect-flash --save
// 20. npm install express-fileupload --save
// 21. npm install -g nodemon
// 22. npm install -g mocha
// 23. npm install chai --save
// 24. npm install chai-http --save
// 25. npm install supertest --save
// 26. npm install -g istanbul
// 27. npm install -g node-inspector
// 28. npm install -g eslint
// 29. npm install -g eslint-plugin-react
// 30. npm install -g eslint-config-airbnb
// 31. npm install -g eslint-plugin-import
// 32. npm install -g eslint-plugin-jsx-a11y
// 33. npm install -g eslint-plugin-react
// 34. npm install -g eslint-plugin-flowtype
// 35. npm install -g eslint-plugin-jsx-control-statements
// 36. npm install -g eslint-plugin-babel
// 37. npm install -g eslint-plugin-react-native
// 38. npm install -g eslint-plugin-react-hooks
// 39. npm install -g eslint-plugin-promise
// 40. npm install -g eslint-plugin-async-await
// 41. npm install -g eslint-plugin-node
// 42. npm install -g eslint-plugin-standard
// 43